---
version: '3'
services:
  crond:
    build: .
    image: crond
  sut:
    image: kiwicom/dgoss
    environment:
      - GOSS_FILES_PATH=/goss
      - GOSS_FILES_STRATEGY=cp
    command: /usr/local/bin/dgoss run crond
    volumes:
      - ./goss:/goss
      - /var/run/docker.sock:/var/run/docker.sock
